Repository greatFredChen/MarkIdea-Frontend, pull requests merged in 2020-06, with the labels that each got.

#33 Fix a bug of stringify circle json data while creating idea
  cloudfunctions/createIdea/index.js
Labels: bug

#34 Added cloud resource deletion when users edit ideas
  cloudfunctions/ideaEdit/index.js
  cloudfunctions/ideaView/index.js
  miniprogram/pages/ideaEdit/ideaEdit.js
Labels: bug

#35 修正README.md
  README.md
Labels: documentation

#36 修改授权模式
  miniprogram/components/AuthorizeDialog/AuthorizeDialog.js
  miniprogram/components/AuthorizeDialog/AuthorizeDialog.json
  miniprogram/components/AuthorizeDialog/AuthorizeDialog.wxml
  miniprogram/components/AuthorizeDialog/AuthorizeDialog.wxss
  miniprogram/components/MenuButton/MenuButton.js
  miniprogram/components/MenuButton/MenuButton.wxml
  miniprogram/components/RefreshButton/RefreshButton.js
  miniprogram/components/RefreshButton/RefreshButton.wxml
  miniprogram/components/RefreshButton/RefreshButton.wxss
  miniprogram/pages/index/index.json
  miniprogram/pages/index/index.wxml
  project.config.json
Labels: enhancement
