Repository greatFredChen/MarkIdea-Frontend, pull requests merged in 2020-05, with the labels that each got.

#2 Create idea split
  .eslintignore
  .eslintrc.js
  .gitignore
  README.md
  cloudfunctions/createIdea/index.js
  cloudfunctions/createIdea/package-lock.json
  cloudfunctions/createIdea/package.json
  cloudfunctions/getIdea/index.js
  cloudfunctions/getIdea/package-lock.json
  cloudfunctions/getIdea/package.json
  cloudfunctions/getOpenId/index.js
  miniprogram/app.js
  miniprogram/app.json
  miniprogram/class/IdeaManager.js
  miniprogram/components/AuthorizeDialog/AuthorizeDialog.js
  miniprogram/components/chatroom/chatroom.js
  miniprogram/components/createPanel/createPanel.js
  miniprogram/components/createPanel/createPanel.json
  miniprogram/components/createPanel/createPanel.wxml
  miniprogram/components/createPanel/createPanel.wxss
  miniprogram/components/detail/detail.js
  miniprogram/components/ideaDialog/ideaDialog.js
  miniprogram/components/ideaDialog/ideaDialog.wxml
  miniprogram/components/wedeaMap/wedeaMap.js
  miniprogram/components/wedeaMap/wedeaMap.json
  miniprogram/components/wedeaMap/wedeaMap.wxml
  miniprogram/components/wedeaMap/wedeaMap.wxss
  miniprogram/pages/index/index.js
  miniprogram/pages/index/index.json
  miniprogram/pages/index/index.wxml
  miniprogram/pages/index/index.wxss
  miniprogram/utils/event.js
  miniprogram/utils/util.js
  package-lock.json
  package.json
Labels: enhancement

#3 增加了敏感文件的配置和实现了两个云函数
  .gitignore
  README.md
  cloudfunctions/getDomainContains/config.json
  cloudfunctions/getDomainContains/index.js
  cloudfunctions/getDomainContains/package-lock.json
  cloudfunctions/getDomainContains/package.json
  cloudfunctions/getLocalDomain/config.json
  cloudfunctions/getLocalDomain/index.js
  cloudfunctions/getLocalDomain/package.json
  miniprogram/app.js
  project.config.json
Labels: enhancement

#4 修复getDomainContains只返回id和eslint的问题
  cloudfunctions/getDomainContains/index.js
  cloudfunctions/getLocalDomain/index.js
  package-lock.json
Labels: bug

#5 Idea view rebase
  cloudfunctions/createIdea/index.js
  cloudfunctions/ideaView/index.js
  cloudfunctions/ideaView/package-lock.json
  cloudfunctions/ideaView/package.json
  miniprogram/app.js
  miniprogram/class/IdeaManager.js
  miniprogram/components/detail/detail.js
  miniprogram/components/detail/detail.json
  miniprogram/components/detail/detail.wxml
  miniprogram/components/detail/detail.wxss
  miniprogram/components/ideaDialog/ideaDialog.wxml
  miniprogram/components/ideaView/ideaView.js
  miniprogram/components/ideaView/ideaView.json
  miniprogram/components/ideaView/ideaView.wxml
  miniprogram/components/ideaView/ideaView.wxss
  miniprogram/components/refreshButton/refreshButton.js
  miniprogram/components/wedeaMap/wedeaMap.js
  miniprogram/pages/index/index.js
  miniprogram/pages/index/index.json
  miniprogram/pages/index/index.wxml
Labels: enhancement

#9 Delete idea
  cloudfunctions/deleteIdea/config.json
  cloudfunctions/deleteIdea/index.js
  cloudfunctions/deleteIdea/package-lock.json
  cloudfunctions/deleteIdea/package.json
  miniprogram/app.js
  miniprogram/components/deleteIdeaDialog/deleteIdeaDialog.js
  miniprogram/components/deleteIdeaDialog/deleteIdeaDialog.json
  miniprogram/components/deleteIdeaDialog/deleteIdeaDialog.wxml
  miniprogram/components/deleteIdeaDialog/deleteIdeaDialog.wxss
  miniprogram/components/ideaView/ideaView.js
  miniprogram/components/ideaView/ideaView.json
  miniprogram/components/ideaView/ideaView.wxml
  miniprogram/components/wedeaMap/wedeaMap.js
Labels: enhancement

#12 refactor idea and marker
  miniprogram/class/IdeaManager.js
  miniprogram/class/MarkerManager.js
  miniprogram/components/createPanel/createPanel.js
  miniprogram/components/createPanel/createPanel.wxml
  miniprogram/components/ideaView/ideaView.js
  miniprogram/components/refreshButton/refreshButton.js
  miniprogram/components/wedeaMap/wedeaMap.js
  miniprogram/components/wedeaMap/wedeaMap.wxml
Labels: enhancement

#14 想法编辑和查看的 UI/UX 优化
  miniprogram/class/IdeaManager.js
  miniprogram/class/IdeaRankCalculator.js
  miniprogram/components/AuthorizeDialog/AuthorizeDialog.wxml
  miniprogram/components/AuthorizeDialog/AuthorizeDialog.wxss
  miniprogram/components/createPanel/createPanel.js
  miniprogram/components/createPanel/createPanel.wxml
  miniprogram/components/deleteIdeaDialog/deleteIdeaDialog.js
  miniprogram/components/deleteIdeaDialog/deleteIdeaDialog.json
  miniprogram/components/deleteIdeaDialog/deleteIdeaDialog.wxml
  miniprogram/components/deleteIdeaDialog/deleteIdeaDialog.wxss
  miniprogram/components/descriptionBox/descriptionBox.wxml
  miniprogram/components/descriptionBox/descriptionBox.wxss
  miniprogram/components/ideaView/ideaView.js
  miniprogram/components/ideaView/ideaView.json
  miniprogram/components/ideaView/ideaView.wxml
  miniprogram/components/ideaView/ideaView.wxss
  miniprogram/components/likeButton/likeButton.js
  miniprogram/components/likeButton/likeButton.wxml
  miniprogram/components/likeButton/likeButton.wxss
  miniprogram/components/wedeaMap/wedeaMap.js
  miniprogram/pages/ideaEdit/ideaEdit.js
  miniprogram/pages/index/index.js
Labels: enhancement

#15 cloud function get_domain_contains return more info from backend
  cloudfunctions/getDomainContains/index.js
Labels: enhancement

#17 More idea icon
  cloudfunctions/getDomainContains/index.js
  miniprogram/class/IdeaManager.js
  miniprogram/class/IdeaRankCalculator.js
  miniprogram/components/chatroom/chatroom.js
  miniprogram/components/chatroom/chatroom.json
  miniprogram/components/chatroom/chatroom.wxml
  miniprogram/components/chatroom/chatroom.wxss
  miniprogram/components/chatroom/dots.gif
  miniprogram/components/chatroom/photo.png
  miniprogram/components/createPanel/createPanel.js
  miniprogram/components/editBox/editBox.wxml
  miniprogram/components/editBox/editBox.wxss
  miniprogram/components/refreshButton/refreshButton.js
  miniprogram/components/wedeaMap/wedeaMap.js
  miniprogram/pages/ideaEdit/ideaEdit.js
  miniprogram/pages/ideaEdit/ideaEdit.wxml
  miniprogram/pages/ideaEdit/ideaEdit.wxss
Labels: enhancement

#18 Import refactor
  cloudfunctions/ideaEdit/index.js
  miniprogram/app.js
  miniprogram/class/Domain.js
  miniprogram/class/DomainManager.js
  miniprogram/class/Idea.js
  miniprogram/class/IdeaConnectManager.js
  miniprogram/class/IdeaManager.js
  miniprogram/class/IdeaRankCalculator.js
  miniprogram/class/ResourceManager.js
  miniprogram/components/connectIdeaDialog/connectIdeaDialog.js
  miniprogram/components/createPanel/createPanel.js
  miniprogram/components/ideaView/ideaView.js
  miniprogram/components/refreshButton/refreshButton.js
  miniprogram/components/wedeaMap/wedeaMap.js
  miniprogram/components/wedeaMap/wedeaMap.wxml
  miniprogram/pages/ideaEdit/ideaEdit.js
  miniprogram/pages/ideaEdit/ideaEdit.wxml
Labels: enhancement

#21 implements likes filter
  miniprogram/class/Filter.js
  miniprogram/class/IdeaManager.js
  miniprogram/class/ResourceManager.js
  miniprogram/components/createPanel/createPanel.js
  miniprogram/components/createPanel/createPanel.wxml
  miniprogram/components/filterItem/filterItem.js
  miniprogram/components/filterItem/filterItem.json
  miniprogram/components/filterItem/filterItem.wxml
  miniprogram/components/filterItem/filterItem.wxss
  miniprogram/components/filterView/filterView.js
  miniprogram/components/filterView/filterView.json
  miniprogram/components/filterView/filterView.wxml
  miniprogram/components/filterView/filterView.wxss
  miniprogram/components/wedeaMap/wedeaMap.js
  miniprogram/pages/index/index.json
  miniprogram/pages/index/index.wxml
Labels: enhancement

#24 implements search id search and jumping in a idea pointer
  miniprogram/class/IdeaManager.js
  miniprogram/components/createPanel/createPanel.js
  miniprogram/components/createPanel/createPanel.wxml
  miniprogram/components/filterView/filterView.wxml
  miniprogram/components/ideaPointer/ideaPointer.js
  miniprogram/components/ideaPointer/ideaPointer.json
  miniprogram/components/ideaPointer/ideaPointer.wxml
  miniprogram/components/ideaPointer/ideaPointer.wxss
  miniprogram/components/searchView/searchView.js
  miniprogram/components/searchView/searchView.json
  miniprogram/components/searchView/searchView.wxml
  miniprogram/components/searchView/searchView.wxss
  miniprogram/components/wedeaMap/wedeaMap.js
  miniprogram/pages/index/index.json
  miniprogram/pages/index/index.wxml
Labels: enhancement

#30 新的音频组件，修复了audio组件不兼容ios的bug
  cloudfunctions/ideaView/index.js
  miniprogram/components/audioBox/audioBox.js
  miniprogram/components/audioBox/audioBox.json
  miniprogram/components/audioBox/audioBox.wxml
  miniprogram/components/audioBox/audioBox.wxss
  miniprogram/components/descriptionBox/descriptionBox.json
  miniprogram/components/descriptionBox/descriptionBox.wxml
  miniprogram/components/editBox/editBox.json
  miniprogram/components/editBox/editBox.wxml
  miniprogram/components/editBox/editBox.wxss
Labels: bug, enhancement
